"""The canonical A-J letter helpers (docs/capability-roadmap.md item F7 /
section 3.6): the ONE place that knows how to render a choice list, build
the JSON-shape letter hint, and parse a model's returned letter, for any
question with 2-10 answer choices.

Before this module existed, every solver/skeptic/judge/gate prompt builder
in src/quorumqa/engine/*.py and benchmark/lever_experiments.py hardcoded
`zip("ABCD", choices)` and `"A|B|C|D"` -- correct only for exactly 4
choices, and silently WRONG (either truncating extra choices or crashing on
an out-of-range letter) for anything else. That is why benchmark/
load_mmlu_pro.py has always trimmed MMLU-Pro's up-to-10-option questions
down to 4, and why MedXpertQA (10 options) could never run through this
engine at all.

Lives in src/quorumqa (not benchmark/) so both `quorumqa.engine.*` and
`benchmark.lever_experiments` can import it without a backwards
benchmark->src->benchmark layering loop.

BACKWARD COMPATIBILITY IS LOAD-BEARING: at n=4 every function here must
reproduce EXACTLY the string/parsing behavior the hardcoded "ABCD" code used
to produce -- every committed benchmark result was generated by those exact
prompts, and a single changed character would silently invalidate cross-run
comparisons. See tests/test_aj_options_offline.py's full-call-fingerprint
equivalence test, which asserts this against a fixture captured from the
pre-refactor code.
"""

from __future__ import annotations

_ALL_LETTERS = "ABCDEFGHIJ"


def letters_for(n: int) -> str:
    """The first `n` letters of A-J, e.g. letters_for(4) == "ABCD",
    letters_for(10) == "ABCDEFGHIJ". Raises ValueError outside 2..10 --
    a 1-choice question has no vote to take, and this engine has no
    vocabulary past "J" (MedXpertQA's own max is 10 options)."""
    if not (2 <= n <= 10):
        raise ValueError(f"letters_for: n must be between 2 and 10 (inclusive), got {n}")
    return _ALL_LETTERS[:n]


def choice_block(choices: list[str]) -> str:
    """"A) ...\\nB) ...\\n..." -- byte-identical to every prompt builder's old
    `"\\n".join(f"{letter}) {c}" for letter, c in zip("ABCD", choices))` when
    len(choices) == 4."""
    letters = letters_for(len(choices))
    return "\n".join(f"{letter}) {c}" for letter, c in zip(letters, choices))


def letter_hint(n_choices: int) -> str:
    """The JSON-shape hint string for a choice count, e.g. letter_hint(4) ==
    "A|B|C|D" (byte-identical to every prompt's old literal "A|B|C|D"),
    letter_hint(10) == "A|B|C|D|E|F|G|H|I|J"."""
    return "|".join(letters_for(n_choices))


def parse_letter(raw, n_choices: int, fallback: str = "A") -> str:
    """Extracts a single uppercase letter from a model's raw JSON field
    value (whatever type it came back as) and validates it against
    letters_for(n_choices); returns `fallback` if it doesn't parse to a
    valid letter for this many choices. `fallback` defaults to "A", the
    same default every hardcoded call site used to fall back to -- callers
    that instead defaulted to e.g. the first solver's letter (the judge
    sites) pass that explicitly. Byte-identical to every prompt parser's old
    `letter if letter in "ABCD" else <fallback>` at n_choices=4 -- INCLUDING
    a deliberately preserved quirk of that old code: `letter in valid` is a
    Python string substring check, and "" is a substring of every string, so
    a missing/empty raw letter never actually hits `fallback` here (or in
    the original code) -- it silently returns "". `fallback` only fires for
    a genuinely invalid non-empty letter (e.g. "Z", "1"). See
    tests/test_aj_options_offline.py::test_parse_letter_preserves_the_old_empty_string_quirk."""
    valid = letters_for(n_choices)
    letter = str(raw).strip().upper()[:1]
    return letter if letter in valid else fallback
